### ISSUE TITLE
第6章のmy_model.pyのMyDNNのforwardメソッドは全ての隠れ層を通していないかもしれない

### ISSUE THREAD

**Issue by Conan-Wen** [ry-takashima/python_asr#2]
@ry-takashima 
音声認識をとても分かりやすくご説明いただき，ありがとうございます．

第6章のコードについて，少し疑問を持っていますが...

`my_model.py`の`MyDNN`の`forward()`メソッドは全ての隠れ層を通していないかもしれません．

------
コンストラクタでは，`self.num_layers`一個につき，`nn.Linear`と`nn.ReLU`二個のレイヤーが`self.hidden`追加されます．
ですので，`self.hidden`の長さは`self.num_layers`の二倍になるはずだと思います．
https://github.com/ry-takashima/python_asr/blob/163cd49a95714b278d6b509715d7c3458c0b15c5/04dnn_hmm/my_model.py#L37-L48

ここで，`range(self.num_layers)`で回したら，隠れ層の半分しか通していないと思います．
https://github.com/ry-takashima/python_asr/blob/163cd49a95714b278d6b509715d7c3458c0b15c5/04dnn_hmm/my_model.py#L65-L67

下記のように，書くべきではありませんか？
```python
    for layer in model.hidden:
        output = layer(output)
```

（初心者なので少し不安です．間違っていたら申し訳ございません．）

**Comment by ry-takashima** [comment]
@Conan-Wen 
本書をお読みになってくださり大変ありがとうございます．
また，ソースコードも丁寧にご確認くださりありがとうございます．
たしかに，ご指摘の通りかと思います．念のため num_layers の半分しか通っていないか動作確認を行った上で，修正を行いたいと思います．しばらくお時間を頂きますが，どうぞよろしくお願いいたします．

**Comment by Conan-Wen** [comment]
@ry-takashima 
ご返信いただき，ありがとうございます！
了解いたしました！ご確認のほど，よろしくお願いいたします！

**Comment by ry-takashima** [comment]
@Conan-Wen 
大変お待たせしました。ご指摘の通り、設定した隠れ層の半分しか通っていませんでしたので、修正をいたしました。
ご指摘ありがとうございました。今後ともどうぞよろしくお願いいたします。

**Comment by Conan-Wen** [comment]
@ry-takashima 

この度はご対応いただき、誠にありがとうございました。

ご著書「Pythonで学ぶ音声認識」を拝読し、音声処理技術や音声認識の歴史から現在に至るまでの手法を理解することができました。大変優れた教科書であり、深く感銘を受けました。

引き続きどうぞよろしくお願いいたします。
